import XCTest

final class FuzzyMatcherTests: XCTestCase {
    func testOrderOfMatchKinds() {
        let exact = FuzzyMatcher.score(query: "notes", candidate: "Notes")!
        let prefix = FuzzyMatcher.score(query: "not", candidate: "Notes")!
        let wordPrefix = FuzzyMatcher.score(query: "set", candidate: "System Settings")!
        let initials = FuzzyMatcher.score(query: "vsc", candidate: "Visual Studio Code")!
        let contains = FuzzyMatcher.score(query: "ote", candidate: "Notes")!
        let subseq = FuzzyMatcher.score(query: "gcm", candidate: "Google Chrome")
        XCTAssertGreaterThan(exact, prefix)
        XCTAssertGreaterThan(prefix, wordPrefix)
        XCTAssertGreaterThan(wordPrefix, initials)
        XCTAssertGreaterThan(initials, contains)
        XCTAssertNotNil(subseq)
        XCTAssertLessThan(subseq!, contains)
    }

    func testNoMatch() {
        XCTAssertNil(FuzzyMatcher.score(query: "xyz", candidate: "Notes"))
        XCTAssertNil(FuzzyMatcher.score(query: "", candidate: "Notes"))
    }

    func testMultiWordRequiresAllTokens() {
        XCTAssertNotNil(FuzzyMatcher.score(query: "sys set", candidate: "System Settings"))
        XCTAssertNil(FuzzyMatcher.score(query: "sys xyz", candidate: "System Settings"))
    }

    func testCaseAndDiacriticsInsensitive() {
        XCTAssertNotNil(FuzzyMatcher.score(query: "CAFE", candidate: "Café"))
    }
}

final class RankerTests: XCTestCase {
    let now = Date(timeIntervalSince1970: 2_000_000_000)

    func testAliasExactMatchIsAlwaysFirst() {
        let items = [
            RankInput(id: "app:Calendar", keys: ["Calendar"], alias: nil, usage: Usage(count: 999, lastUsed: now)),
            RankInput(id: "cmd:clipboard", keys: ["Clipboard History"], alias: "c", usage: nil),
        ]
        XCTAssertEqual(Ranker.rank(query: "c", items: items, now: now).first, "cmd:clipboard")
        XCTAssertEqual(Ranker.rank(query: "C", items: items, now: now).first, "cmd:clipboard")
    }

    func testAliasDoesNotHijackLongerQuery() {
        let items = [
            RankInput(id: "app:Calendar", keys: ["Calendar"], alias: nil, usage: nil),
            RankInput(id: "cmd:clipboard", keys: ["Clipboard History"], alias: "c", usage: nil),
        ]
        XCTAssertEqual(Ranker.rank(query: "cal", items: items, now: now), ["app:Calendar"])
    }

    func testFrecencyBreaksTies() {
        let items = [
            RankInput(id: "a", keys: ["Terminal"], alias: nil, usage: nil),
            RankInput(id: "b", keys: ["Terminus"], alias: nil, usage: Usage(count: 5, lastUsed: now)),
        ]
        XCTAssertEqual(Ranker.rank(query: "term", items: items, now: now).first, "b")
    }

    func testOldUsageDecays() {
        let recent = Frecency.value(Usage(count: 10, lastUsed: now), now: now)
        let old = Frecency.value(Usage(count: 10, lastUsed: now.addingTimeInterval(-28 * 86_400)), now: now)
        XCTAssertEqual(old, recent / 4, accuracy: 0.001)
        XCTAssertEqual(Frecency.bonus(nil, now: now), 0)
        XCTAssertLessThanOrEqual(Frecency.bonus(Usage(count: 100_000, lastUsed: now), now: now), 200)
    }

    func testEmptyQueryReturnsNothing() {
        XCTAssertEqual(Ranker.rank(query: "  ", items: [RankInput(id: "a", keys: ["A"], alias: nil, usage: nil)], now: now), [])
    }
}

final class ClipboardPolicyTests: XCTestCase {
    func testSkipsConcealedTransientAutoGenerated() {
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["org.nspasteboard.TransientType"]))
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["org.nspasteboard.AutoGeneratedType"]))
        XCTAssertFalse(ClipboardPolicy.shouldSkip(types: ["public.utf8-plain-text"]))
    }

    func testKindPriority() {
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: true, text: "/a", hasImage: true), .file)
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: false, text: "hello", hasImage: true), .text)
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: false, text: "  \n", hasImage: true), .image)
        XCTAssertNil(ClipboardPolicy.kind(hasFiles: false, text: nil, hasImage: false))
    }

    func testDedupeKeyDistinguishesKinds() {
        XCTAssertNotEqual(ClipboardPolicy.dedupeKey(kind: .text, payload: "/tmp/a"),
                          ClipboardPolicy.dedupeKey(kind: .file, payload: "/tmp/a"))
        XCTAssertEqual(ClipboardPolicy.dedupeKey(kind: .text, payload: "x"), ClipboardPolicy.dedupeKey(kind: .text, payload: "x"))
    }

    func testCutoffIs90Days() {
        let now = Date(timeIntervalSince1970: 2_000_000_000)
        XCTAssertEqual(now.timeIntervalSince(ClipboardPolicy.cutoff(now: now)), 90 * 86_400)
    }
}

final class EmojiSearchTests: XCTestCase {
    let entries = [
        EmojiEntry(e: "😀", n: "grinning face", j: "にっこり笑う", k: ["smile", "happy", "笑顔"], g: "Smileys"),
        EmojiEntry(e: "👍", n: "thumbs up", j: "サムズアップ", k: ["+1", "good", "いいね"], g: "People"),
        EmojiEntry(e: "🇯🇵", n: "flag: Japan", j: "旗: 日本", k: ["flag", "旗"], g: "Flags"),
    ]

    func testEnglishNameAndKeyword() {
        XCTAssertEqual(EmojiSearch.search("thumb", in: entries).first?.e, "👍")
        XCTAssertEqual(EmojiSearch.search("good", in: entries).first?.e, "👍")
        XCTAssertEqual(EmojiSearch.search("japan", in: entries).first?.e, "🇯🇵")
    }

    func testJapaneseKeyword() {
        XCTAssertEqual(EmojiSearch.search("いいね", in: entries).map(\.e), ["👍"])
        XCTAssertEqual(EmojiSearch.search("笑顔", in: entries).map(\.e), ["😀"])
    }

    func testEmptyQueryKeepsOrder() {
        XCTAssertEqual(EmojiSearch.search("", in: entries).map(\.e), ["😀", "👍", "🇯🇵"])
    }

    func testUsageBoostsResult() {
        let many = [
            EmojiEntry(e: "A", n: "face one", j: nil, k: [], g: ""),
            EmojiEntry(e: "B", n: "face two", j: nil, k: [], g: ""),
        ]
        let usage = ["B": Usage(count: 10, lastUsed: Date())]
        XCTAssertEqual(EmojiSearch.search("face", in: many, usage: usage).first?.e, "B")
    }
}

final class AppPathRulesTests: XCTestCase {
    func testNestedAppIsExcluded() {
        XCTAssertTrue(AppPathRules.isNestedApp("/Applications/Foo.app/Contents/Library/LoginItems/Bar.app"))
        XCTAssertFalse(AppPathRules.isNestedApp("/Applications/Utilities/Terminal.app"))
    }

    func testRomanized() {
        XCTAssertEqual(AppPathRules.romanized("メモ"), "memo")
        XCTAssertNil(AppPathRules.romanized("Notes"))
    }
}

final class CalculatorTests: XCTestCase {
    func testPrecedenceAndParentheses() {
        XCTAssertEqual(Calculator.evaluate("3 + (34 *2)"), 71)
        XCTAssertEqual(Calculator.evaluate("2 + 3 * 4"), 14)
        XCTAssertEqual(Calculator.evaluate("(2 + 3) * 4"), 20)
        XCTAssertEqual(Calculator.evaluate("10 - 4 - 3"), 3) // 左結合
        XCTAssertEqual(Calculator.evaluate("2 ^ 3 ^ 2"), 512) // 右結合
        XCTAssertEqual(Calculator.evaluate("-2 ^ 2"), -4)
        XCTAssertEqual(Calculator.evaluate("10 % 3"), 1)
        XCTAssertEqual(Calculator.evaluate("7 / 2"), 3.5)
        XCTAssertEqual(Calculator.evaluate("3 * -2"), -6)
        XCTAssertEqual(Calculator.evaluate("-(2 + 3) * 2"), -10)
    }

    func testAlternativeSymbolsAndNumbers() {
        XCTAssertEqual(Calculator.evaluate("6 × 7"), 42)
        XCTAssertEqual(Calculator.evaluate("9 ÷ 3"), 3)
        XCTAssertEqual(Calculator.evaluate("1,000 * 3"), 3000)
        XCTAssertEqual(Calculator.evaluate(".5 + 1."), 1.5)
    }

    func testAutoClosesTrailingParentheses() {
        XCTAssertEqual(Calculator.evaluate("3 + (34 * 2"), 71)
        XCTAssertEqual(Calculator.evaluate("((1 + 2) * 3"), 9)
    }

    /// 二項演算子の無い入力はアプリ検索に譲る
    func testNotAnExpression() {
        for q in ["", "3", "-3", "(3)", "+", "safari", "3 apples", "1.2.3 + 1", "c"] {
            XCTAssertNil(Calculator.evaluate(q), q)
        }
    }

    func testIncompleteOrInvalid() {
        for q in ["3 +", "3 * ", "(3 + 4))", "3 + 4)", "(3)(4)", "3 4 + 1", "1 / 0", "0 / 0", "5 % 0", "10 ^ 400"] {
            XCTAssertNil(Calculator.evaluate(q), q)
        }
    }

    func testFormat() {
        XCTAssertEqual(Calculator.format(Calculator.evaluate("0.1 + 0.2")!, grouping: false), "0.3")
        XCTAssertEqual(Calculator.format(1234567.5, grouping: true), "1,234,567.5")
        XCTAssertEqual(Calculator.format(1234567.5, grouping: false), "1234567.5")
        XCTAssertEqual(Calculator.format(71, grouping: true), "71")
        XCTAssertEqual(Calculator.format(-0.25, grouping: true), "-0.25")
        XCTAssertEqual(Calculator.format(Calculator.evaluate("0 * -1")!, grouping: false), "0")
        XCTAssertEqual(Calculator.format(Calculator.evaluate("1 / 3")!, grouping: false), "0.333333333333333")
        XCTAssertEqual(Calculator.format(Calculator.evaluate("2 ^ 60")!, grouping: false), "1.15292150460685e+18")
    }
}

final class SystemCommandTests: XCTestCase {
    func testOnlyIrreversibleActionsNeedConfirmation() {
        XCTAssertFalse(SystemAction.sleep.needsConfirmation)
        XCTAssertFalse(SystemAction.lockScreen.needsConfirmation)
        XCTAssertTrue(SystemAction.restart.needsConfirmation)
        XCTAssertTrue(SystemAction.shutDown.needsConfirmation)
        XCTAssertTrue(SystemAction.quitAllApps.needsConfirmation)
        XCTAssertEqual(SystemAction.allCases.filter(\.returnsToPreviousApp), [.sleep, .lockScreen])
    }

    func testQuitAllKeepsFinderSelfAndBackgroundApps() {
        XCTAssertTrue(QuitAllPolicy.shouldQuit(bundleID: "com.apple.Safari", isRegular: true, isSelf: false))
        XCTAssertTrue(QuitAllPolicy.shouldQuit(bundleID: nil, isRegular: true, isSelf: false))
        XCTAssertFalse(QuitAllPolicy.shouldQuit(bundleID: "com.apple.finder", isRegular: true, isSelf: false))
        XCTAssertFalse(QuitAllPolicy.shouldQuit(bundleID: "io.github.nyshk97.mycast", isRegular: true, isSelf: true))
        // メニューバー常駐（accessory）・バックグラウンドは閉じない
        XCTAssertFalse(QuitAllPolicy.shouldQuit(bundleID: "com.example.agent", isRegular: false, isSelf: false))
    }

    func testSearchFindsSystemActions() {
        let items = SystemAction.allCases.map { a in
            RankInput(id: a.rawValue, keys: a.keys, alias: nil, usage: nil)
        }
        let now = Date()
        XCTAssertEqual(Ranker.rank(query: "restart", items: items, now: now).first, "restart")
        XCTAssertEqual(Ranker.rank(query: "reboot", items: items, now: now).first, "restart")
        XCTAssertEqual(Ranker.rank(query: "shut", items: items, now: now).first, "shutDown")
        XCTAssertEqual(Ranker.rank(query: "sleep", items: items, now: now).first, "sleep")
        XCTAssertEqual(Ranker.rank(query: "lock", items: items, now: now).first, "lockScreen")
        XCTAssertEqual(Ranker.rank(query: "close all", items: items, now: now).first, "quitAllApps")
        XCTAssertEqual(Ranker.rank(query: "quit all", items: items, now: now).first, "quitAllApps")
        XCTAssertEqual(Ranker.rank(query: "saikidou", items: items, now: now).first, "restart")
        XCTAssertEqual(Ranker.rank(query: "shatto", items: items, now: now).first, "shutDown")
    }
}

final class ScreenPickTests: XCTestCase {
    // 内蔵（主画面）の右に Studio Display を上揃えで並べた配置
    let frames = [CGRect(x: 0, y: 0, width: 1728, height: 1117),
                  CGRect(x: 1728, y: -323, width: 2560, height: 1440)]

    func testPicksScreenUnderPoint() {
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 500, y: 500), in: frames), 0)
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 3000, y: 800), in: frames), 1)
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 3000, y: -300), in: frames), 1)
    }

    func testTopEdgeCountsAsInside() {
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 3000, y: 1117), in: frames), 1)
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 4288, y: 1117), in: frames), 1)
    }

    func testFallsBackToPrimary() {
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: -100, y: 500), in: frames), 0)
        XCTAssertEqual(ScreenPick.index(containing: CGPoint(x: 10, y: 10), in: []), 0)
    }
}
