import XCTest

final class FuzzyMatcherTests: XCTestCase {
    func testOrderOfMatchKinds() {
        let exact = FuzzyMatcher.score(query: "notes", candidate: "Notes")!
        let prefix = FuzzyMatcher.score(query: "not", candidate: "Notes")!
        let wordPrefix = FuzzyMatcher.score(query: "set", candidate: "System Settings")!
        let initials = FuzzyMatcher.score(query: "vsc", candidate: "Visual Studio Code")!
        let contains = FuzzyMatcher.score(query: "ote", candidate: "Notes")!
        let subseq = FuzzyMatcher.score(query: "gcm", candidate: "Google Chrome")
        XCTAssertGreaterThan(exact, prefix)
        XCTAssertGreaterThan(prefix, wordPrefix)
        XCTAssertGreaterThan(wordPrefix, initials)
        XCTAssertGreaterThan(initials, contains)
        XCTAssertNotNil(subseq)
        XCTAssertLessThan(subseq!, contains)
    }

    func testNoMatch() {
        XCTAssertNil(FuzzyMatcher.score(query: "xyz", candidate: "Notes"))
        XCTAssertNil(FuzzyMatcher.score(query: "", candidate: "Notes"))
    }

    func testMultiWordRequiresAllTokens() {
        XCTAssertNotNil(FuzzyMatcher.score(query: "sys set", candidate: "System Settings"))
        XCTAssertNil(FuzzyMatcher.score(query: "sys xyz", candidate: "System Settings"))
    }

    func testCaseAndDiacriticsInsensitive() {
        XCTAssertNotNil(FuzzyMatcher.score(query: "CAFE", candidate: "Café"))
    }
}

final class RankerTests: XCTestCase {
    let now = Date(timeIntervalSince1970: 2_000_000_000)

    func testAliasExactMatchIsAlwaysFirst() {
        let items = [
            RankInput(id: "app:Calendar", keys: ["Calendar"], alias: nil, usage: Usage(count: 999, lastUsed: now)),
            RankInput(id: "cmd:clipboard", keys: ["Clipboard History"], alias: "c", usage: nil),
        ]
        XCTAssertEqual(Ranker.rank(query: "c", items: items, now: now).first, "cmd:clipboard")
        XCTAssertEqual(Ranker.rank(query: "C", items: items, now: now).first, "cmd:clipboard")
    }

    func testAliasDoesNotHijackLongerQuery() {
        let items = [
            RankInput(id: "app:Calendar", keys: ["Calendar"], alias: nil, usage: nil),
            RankInput(id: "cmd:clipboard", keys: ["Clipboard History"], alias: "c", usage: nil),
        ]
        XCTAssertEqual(Ranker.rank(query: "cal", items: items, now: now), ["app:Calendar"])
    }

    func testFrecencyBreaksTies() {
        let items = [
            RankInput(id: "a", keys: ["Terminal"], alias: nil, usage: nil),
            RankInput(id: "b", keys: ["Terminus"], alias: nil, usage: Usage(count: 5, lastUsed: now)),
        ]
        XCTAssertEqual(Ranker.rank(query: "term", items: items, now: now).first, "b")
    }

    func testOldUsageDecays() {
        let recent = Frecency.value(Usage(count: 10, lastUsed: now), now: now)
        let old = Frecency.value(Usage(count: 10, lastUsed: now.addingTimeInterval(-28 * 86_400)), now: now)
        XCTAssertEqual(old, recent / 4, accuracy: 0.001)
        XCTAssertEqual(Frecency.bonus(nil, now: now), 0)
        XCTAssertLessThanOrEqual(Frecency.bonus(Usage(count: 100_000, lastUsed: now), now: now), 200)
    }

    func testEmptyQueryReturnsNothing() {
        XCTAssertEqual(Ranker.rank(query: "  ", items: [RankInput(id: "a", keys: ["A"], alias: nil, usage: nil)], now: now), [])
    }
}

final class ClipboardPolicyTests: XCTestCase {
    func testSkipsConcealedTransientAutoGenerated() {
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["org.nspasteboard.TransientType"]))
        XCTAssertTrue(ClipboardPolicy.shouldSkip(types: ["org.nspasteboard.AutoGeneratedType"]))
        XCTAssertFalse(ClipboardPolicy.shouldSkip(types: ["public.utf8-plain-text"]))
    }

    func testKindPriority() {
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: true, text: "/a", hasImage: true), .file)
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: false, text: "hello", hasImage: true), .text)
        XCTAssertEqual(ClipboardPolicy.kind(hasFiles: false, text: "  \n", hasImage: true), .image)
        XCTAssertNil(ClipboardPolicy.kind(hasFiles: false, text: nil, hasImage: false))
    }

    func testDedupeKeyDistinguishesKinds() {
        XCTAssertNotEqual(ClipboardPolicy.dedupeKey(kind: .text, payload: "/tmp/a"),
                          ClipboardPolicy.dedupeKey(kind: .file, payload: "/tmp/a"))
        XCTAssertEqual(ClipboardPolicy.dedupeKey(kind: .text, payload: "x"), ClipboardPolicy.dedupeKey(kind: .text, payload: "x"))
    }

    func testCutoffIs90Days() {
        let now = Date(timeIntervalSince1970: 2_000_000_000)
        XCTAssertEqual(now.timeIntervalSince(ClipboardPolicy.cutoff(now: now)), 90 * 86_400)
    }
}

final class EmojiSearchTests: XCTestCase {
    let entries = [
        EmojiEntry(e: "😀", n: "grinning face", j: "にっこり笑う", k: ["smile", "happy", "笑顔"], g: "Smileys"),
        EmojiEntry(e: "👍", n: "thumbs up", j: "サムズアップ", k: ["+1", "good", "いいね"], g: "People"),
        EmojiEntry(e: "🇯🇵", n: "flag: Japan", j: "旗: 日本", k: ["flag", "旗"], g: "Flags"),
    ]

    func testEnglishNameAndKeyword() {
        XCTAssertEqual(EmojiSearch.search("thumb", in: entries).first?.e, "👍")
        XCTAssertEqual(EmojiSearch.search("good", in: entries).first?.e, "👍")
        XCTAssertEqual(EmojiSearch.search("japan", in: entries).first?.e, "🇯🇵")
    }

    func testJapaneseKeyword() {
        XCTAssertEqual(EmojiSearch.search("いいね", in: entries).map(\.e), ["👍"])
        XCTAssertEqual(EmojiSearch.search("笑顔", in: entries).map(\.e), ["😀"])
    }

    func testEmptyQueryKeepsOrder() {
        XCTAssertEqual(EmojiSearch.search("", in: entries).map(\.e), ["😀", "👍", "🇯🇵"])
    }

    func testUsageBoostsResult() {
        let many = [
            EmojiEntry(e: "A", n: "face one", j: nil, k: [], g: ""),
            EmojiEntry(e: "B", n: "face two", j: nil, k: [], g: ""),
        ]
        let usage = ["B": Usage(count: 10, lastUsed: Date())]
        XCTAssertEqual(EmojiSearch.search("face", in: many, usage: usage).first?.e, "B")
    }
}

final class AppPathRulesTests: XCTestCase {
    func testNestedAppIsExcluded() {
        XCTAssertTrue(AppPathRules.isNestedApp("/Applications/Foo.app/Contents/Library/LoginItems/Bar.app"))
        XCTAssertFalse(AppPathRules.isNestedApp("/Applications/Utilities/Terminal.app"))
    }

    func testRomanized() {
        XCTAssertEqual(AppPathRules.romanized("メモ"), "memo")
        XCTAssertNil(AppPathRules.romanized("Notes"))
    }
}
