import Foundation

/// クリップボード履歴の記録ルール（純粋関数。NSPasteboard には触らない）
enum ClipboardPolicy {
    static let retentionDays = 90

    /// パスワードマネージャ等が「記録しないで」と印を付けるための型（nspasteboard.org の慣習）
    static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    enum Kind: String { case text, image, file }

    static func shouldSkip(types: [String]) -> Bool {
        types.contains(where: skipTypes.contains)
    }

    /// 何として記録するか。ファイル参照 > テキスト > 画像 の順
    /// （Office 系は文字列と画像を同時に載せるので、文字列があれば文字列として扱う）
    static func kind(hasFiles: Bool, text: String?, hasImage: Bool) -> Kind? {
        if hasFiles { return .file }
        if let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return .text }
        if hasImage { return .image }
        return nil
    }

    static func cutoff(now: Date) -> Date {
        now.addingTimeInterval(-Double(retentionDays) * 86_400)
    }

    /// 同じ内容の判定に使うキー。種類を含めて、同じ文字列のテキストとファイルパスを区別する
    static func dedupeKey(kind: Kind, payload: String) -> String {
        "\(kind.rawValue):\(payload)"
    }
}
